spring: #Redis配置
  redis:
    host: 192.168.138.130
    port: 6379
    password: 123.com
    jedis:
      pool:
        max-active: 8 #连接池最大连接数(负值表示没有限制)
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 #连接池最大空闲连接
        min-idle: 0 #连接池最小空闲连接
    timeout: 50 #连接超时时间（毫秒）