######  tomcat config start ######
server:
  port: 8081
  servlet:
    context-path: /dev-component
  tomcat:
    uri-encoding: UTF-8
######  thymeleaf config start ######
spring:
  thymeleaf:
    prefix: classpath:/templates/ 
    cache: false
    suffix: .html
######  data config start ######
  datasource:
    url: jdbc:mysql://192.168.138.130/dataX2?characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
######  log config start ######
logging:
  level:
    com.cetiti.owls: debug